name: Gitleaks Secret Detection

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          # Install Gitleaks on Ubuntu
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.9.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks

      - name: Verify Gitleaks Installation
        run: gitleaks --version  # To check if the binary was installed correctly

      - name: Run Gitleaks
        run: gitleaks detect --repo-path=. --exit-code=1 --verbose