name: Gitleaks Secret Detection

on:
  push:
    branches:
      - master  # Use your actual branch name, which is `master` in your case
  pull_request:
    branches:
      - master  # This ensures the PR to the `master` branch is checked for secrets

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.9.0/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Run Gitleaks
      run: gitleaks detect . --exit-code=1 --verbose