name: Gitleaks Secret Detection

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          # Download Gitleaks
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.9.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          
          # Check if the download was successful
          if [ ! -f /usr/local/bin/gitleaks ]; then
            echo "Gitleaks download failed!"
            exit 1
          fi

          # Make it executable
          chmod +x /usr/local/bin/gitleaks

      - name: Verify Gitleaks Installation
        run: |
          if ! command -v gitleaks &> /dev/null; then
            echo "Gitleaks could not be installed!"
            exit 1
          fi
          gitleaks --version

      - name: Run Gitleaks
        run: gitleaks detect --repo-path=. --exit-code=1 --verbose
