name: Gitleaks Secret Detection

on:
  push:
    branches:
      - master  # Run the workflow on pushes to `master` branch
  pull_request:
    branches:
      - master  # Run the workflow for PRs to the `master` branch

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          # Install Gitleaks on Ubuntu
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks
          ls /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks detect . --exit-code=1 --verbose